variants : 
  basis : {path: /xslt/m4a_view.xslt}
  basis_wm : {path: /xslt/wm_view.xslt}
  basis_studiovo : {path: /xslt/studiovo_view.xslt}
  studiovo_view : {path: /xslt/studiovo_view.xslt}
  pulseon_studiovo : {path: /xslt/studiovo_pulseon.xslt}
  pulseon_studiovo_item : {path: /xslt/studiovo_pulseon_item.xslt}
  wm_view : {path: /xslt/wm_view.xslt}
  m4a_view : {path: /xslt/m4a_view.xslt}
  m4a_view_old : {path: /xslt/m4a_view_old.xslt}
  m4a_view_mbo : {path: /xslt/m4a_view_mbo.xslt}
  m4a_view_en : {path: /xslt/m4a_view_en.xslt}
  m4a_view_dedicon : {path: /xslt/m4a_view_dedicon.xslt}
  m4a_view_pulseon : {path: /xslt/m4a_view_pulseon.xslt}
  m4a_editor : {path: /xslt/m4a_editor.xslt}
  m4a_insert : {path: /xslt/m4a_insert.xslt}
  m4a_remove : {path: /xslt/m4a_remove.xslt}
  m4a_inverse : {path: /xslt/m4a_inverse.xslt}
  
resultVariants :
  studiovo_result: {path: /xslt/studiovo_result.xslt}
  
loginVariants :
  studiovo_login: {path: /xslt/studiovo_login.xslt}

roles :
  - admin
  - editor_saba
  - editor_m4a
  - editor_concept_alt
  - editor_test
  
repos :
  wm :
    id : wm-2015-07-16
    path: content-wm/concept
    edit_permission: 
    defaultVariant: wm_view
  m4a :
    id : m4a-2015-07-20
    path: content-ma/concept
    edit_permission: editor_m4a
    defaultVariant: m4a_view_old
  m4a2015 :
    id : m4a2015-2015-07-16
    path: content-ma/math4all-2015
    edit_permission: editor_m4a
    defaultVariant: m4a_view
  m4a_en :
    id : m4a_en-2013-07-19
    path: content-ma/saba
    baseRepo : m4a
    edit_permission: editor_saba
    defaultVariant: m4a_view_en
  math4mbo :
    id : ma-math4mbo-2017-09-29
    path: content-ma/math4mbo
    edit_permission: editor_m4a
    defaultVariant: m4a_view
  studiovo :
    id : studiovo-2013-07-19
    path: content-studiovo/publish
    edit_permission: 
    defaultVariant: studiovo_view
    defaultResultVariant: studiovo_result
    defaultLoginVariant: studiovo_login
  studiovo_concept :
    id : studiovo-2013-07-19
    path: content-studiovo/concept
    edit_permission: 
    defaultVariant: studiovo_view
    defaultResultVariant: studiovo_result
    defaultLoginVariant: studiovo_login
  studiovo_kennisbank :
    id : studiovo-kennisbank-2013-12-29
    path: content-studiovo/kennisbank
    edit_permission: 
    defaultVariant: studiovo_view

userFile : /data/content-overview/users.yaml
contentRoot : /data/

mail_host : smtp.xs4all.nl
mail_smtp_port : 587
mail_username : gaj2
mail_password : mjd1602S
admin_mail : m.slob@math4all.nl

 