variants : 
  basis : {path: /xslt/m4a_view.xslt}
  m4a_view : {path: /xslt/m4a_view.xslt}
  m4a_editor : {path: /xslt/m4a_editor.xslt}
  m4a_inverse : {path: /xslt/m4a_inverse.xslt}

roles :
  - admin
  - editor_test
  - editor_malmberg
  
repos :
  malmberg :
    path: 
    edit_permission: editor_malmberg
    defaultVariant: m4a_view
    componentsURL: /opt/sw/mathplus/data/leerlijnen/components.xml
    threadsURL: /opt/sw/mathplus/data/leerlijnen/threads.xml
  test :
    path: content-ma/test
    baseRepo : m4a
    edit_permission: editor_test
    defaultVariant: m4a_view

userFile : /opt/sw/mathplus/data/users_malmberg.yaml
contentRoot : /opt/sw/mathplus/data/
entitiesFile : /opt/sw/mathplus/data/entities.xml

mail_host : localhost
mail_smtp_port : 25
mail_username :  
mail_password :  
admin_mail : m.slob@math4all.nl

 