variants : 
  basis : {path: /xslt/m4a_view.xslt}
  m4a_view : {path: /xslt/m4a_view.xslt}
  m4a_editor : {path: /xslt/m4a_editor.xslt}
  m4a_inverse : {path: /xslt/m4a_inverse.xslt}

roles :
  - admin
  - editor_test
  - editor_malmberg
  
repos :
  malmberg :
    path: 
    edit_permission: editor_malmberg
    defaultVariant: m4a_view
    componentsURL: /data/leerlijnen/components.xml
    threadsURL: /data/leerlijnen/threads.xml
  test :
    path: content-ma/test
    baseRepo : m4a
    edit_permission: editor_test
    defaultVariant: m4a_view

userFile : /data/users.yaml
contentRoot : /data/
entitiesFile : /data/entities.xml

mail_host : smtp.xs4all.nl
mail_smtp_port : 587
mail_username : gaj2
mail_password : mjd1602S
admin_mail : m.slob@math4all.nl

 