variants : 
  basis : {path: /xslt/m4a_view.xslt}
  basis_wm : {path: /xslt/wm_view.xslt}
  basis_studiovo : {path: /xslt/studiovo_view.xslt}
  m4a_editor : {path: /xslt/m4a_editor.xslt}
  m4a_insert : {path: /xslt/m4a_insert.xslt}
  m4a_remove : {path: /xslt/m4a_remove.xslt}
  m4a_inverse : {path: /xslt/m4a_inverse.xslt}

roles :
  - admin
  - editor_saba
  - editor_concept_alt
  
repos :
  wm :
    path: content-wm/final
    edit_permission: 
  m4a :
    path: content-ma/final
    edit_permission: 
  wm_concept :
    path: content-wm/concept
    edit_permission: 
  m4a_concept :
    path: content-ma/concept
    edit_permission: 
  m4a_concept_alt :
    path: content-ma/concept_alt
    edit_permission: editor_concept_alt
    baseRepo : m4a_concept
  saba :
    path: content-ma/saba
    edit_permission: editor_saba
    baseRepo : m4a_concept

defaultRepo : m4a_concept
userFile : /Users/martijnslob/Dropbox/Math4all/MathUnited/src/main/webapp/users.yaml
contentRoot : /Users/martijnslob/data/
componentsFile : /Users/martijnslob/data/content-overview/components.xml
entitiesFile : /Users/martijnslob/data/content-overview/entities.xml

mail_host : smtp.xs4all.nl
mail_smtp_port : 587
mail_username : gaj2
mail_password : mjd1602S
admin_mail : m.slob@math4all.nl

  